const products = [
    {

        title:'Coaching',
        description: '150h of pure coaching stuff',
        author: 'Sam Smith',
        rate:4,
        price:99,
        isBestseller:true,
        inCart:false,
        amount:0,
        id: 1,
    },
    {
        title:'Graphics',
        description: 'Using Adobe, Figma and Gimp',
        author: 'Adam Doe',
        price:59,
        rate:4,
        isBestseller:true,
        inCart:false,
        amount:0,
        id: 2,
    },
    {
        title:'Copywriting',
        description: 'You are going to become top paid copywriter after this lecture. Author has 10 years of experience as copywriter at Google',
        author: 'Sam Adams',
        rate:4.6,
        price:349,
        isBestseller:true,
        inCart:false,
        amount:0,
        id: 3,
    },
    {
        title:'Content Cretor',
        description: 'We will teach you how to be creative',
        author: 'John Adams',
        rate:4.6,
        price:49,
        isBestseller:true,
        inCart:false,
        amount:0,
        id: 4,
    },
    {
        title:'Databases',
        description: '30h of lectures + 50h of exercises',
        author: 'Smith Jones',
        rate:4.4,
        price:49,
        isBestseller:true,
        inCart:false,
        amount:0,
        id: 5,
    },
    {
        title:'Programming',
        description: '#1 on the market. Free support',
        author: 'Adam Chris',
        rate:5,
        price:149,
        isBestseller:true,
        inCart:false,
        amount:0,
        id: 6,
    },
    {
        title:'Coaching',
        description: '150h of pure coaching stuff',
        author: 'Sam Smith',
        rate:4.5,
        price:99,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 7,
    },
    {
        title:'Graphics',
        description: 'Using Adobe, Figma and Gimp',
        author: 'Adam Doe',
        rate:4.5,
        price:59,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 8,
    },
    {
        title:'Copywriting',
        description: 'You are going to become top paid copywriter after this lecture. Author has 10 years of experience as copywriter at Google',
        author: 'Sam Adams',
        rate:4.5,
        price:349,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 9,
    },
    {
        title:'Content Cretor',
        description: 'We will teach you how to be creative',
        author: 'John Adams',
        rate:4.5,
        price:49,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 10,
    },
    {
        title:'Databases',
        description: '30h of lectures + 50h of exercises',
        author: 'Smith Jones',
        rate:4.5,
        price:49,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 11,
    },
    {
        title:'Programming',
        description: '#1 on the market. Free support',
        author: 'Adam Chris',
        rate:4.5,
        price:149,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 12,
    },
    {
        title:'Coaching',
        description: '150h of pure coaching stuff',
        author: 'Sam Smith',
        rate:4.5,
        price:99,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 13,
    },
    {
        title:'Graphics',
        description: 'Using Adobe, Figma and Gimp',
        author: 'Adam Doe',
        rate:4.5,
        price:59,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 14,
    },
    {
        title:'Copywriting',
        description: 'You are going to become top paid copywriter after this lecture. Author has 10 years of experience as copywriter at Google',
        author: 'Sam Adams',
        rate:4.5,
        price:349,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 15,
    },
    {
        title:'Content Cretor',
        description: 'We will teach you how to be creative',
        author: 'John Adams',
        rate:4.5,
        price:49,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 16,
    },
    {
        title:'Databases',
        description: '30h of lectures + 50h of exercises',
        author: 'Smith Jones',
        rate:4.5,
        price:49,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 17,
    },
    {
        title:'Programming',
        description: '#1 on the market. Free support',
        author: 'Adam Chris',
        rate:4.5,
        price:149,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 18,
    },
    {
        title:'Coaching',
        description: '150h of pure coaching stuff',
        author: 'Sam Smith',
        rate:4.5,
        price:99,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 19,
    },
    {
        title:'Graphics',
        description: 'Using Adobe, Figma and Gimp',
        author: 'Adam Doe',
        rate:4.5,
        price:59,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 20,
    },
    {
        title:'Copywriting',
        description: 'You are going to become top paid copywriter after this lecture. Author has 10 years of experience as copywriter at Google',
        author: 'Sam Adams',
        rate:4.5,
        price:349,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 21,
    },
    {
        title:'Content Cretor',
        description: 'We will teach you how to be creative',
        author: 'John Adams',
        rate:4.5,
        price:49,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 22,
    },
    {
        title:'Databases',
        description: '30h of lectures + 50h of exercises',
        author: 'Smith Jones',
        rate:4.5,
        price:49,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 23,
    },
    {
        title:'Programming',
        description: '#1 on the market. Free support',
        author: 'Adam Chris',
        rate:4.5,
        price:149,
        isBestseller:false,
        inCart:false,
        amount:0,
        id: 24,
    },
]

export default products;